In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

In [2]:
from coffee.extract import extract_cafe, extract_cappuccino_index
from coffee.transform import clean_cafe_data, clean_cappuccino_data

cafe = clean_cafe_data(extract_cafe())
cappuccino_index = clean_cappuccino_data(extract_cappuccino_index())

In [3]:
cafe.head()

,country,city,urban,suburban,rural,hourly_wage_gbp,price_gbp,original_currency,price,hourly_wage
0,Denmark,Copenhagen,True,False,False,16.04,10.31,DKK - Danish Krone,90.0,140.00
1,China,Shenzhen,True,False,False,3.29,9.44,CNY - Yuan Renminbi,86.0,30.00
2,USA,West Richland,False,True,False,13.25,8.89,USD - US dollar,12.0,17.88
3,Switzerland,St. Moritz,False,False,True,24.50,8.26,CHF - Swiss Franc,9.0,26.70
4,Denmark,Copenhagen,True,False,False,16.04,7.45,DKK - Danish Krone,65.0,140.00

In [5]:
cappuccino_index.tail()

     country       index   n  minutes  seconds index_as_time
82   Vietnam  162.431762   6      162       25        162:25
83     India  172.180851  11      172       10        172:10
84  Djibouti  172.758621   1      172       45        172:45
85     Qatar  186.993865   1      186       59        186:59
86  Pakistan  277.037037   2      277        2        277:02

The 2 data sets loaded fine, which mean the pipeline works.
Furthermore, as the 2 datasets already got cleaned by the the ET(L) pipeline, they are ready for the analysis step.

In [7]:
cafe.describe()

       hourly_wage_gbp    price_gbp         price   hourly_wage
count      2425.000000  2425.000000   2425.000000   2425.000000
mean         11.225472     3.375348    375.130586    295.273476
std           4.668192     0.837308   3733.597427   2213.575373
min           0.170000     0.830000      1.200000      0.670000
25%           8.500000     2.830000      3.900000     13.000000
50%          12.210000     3.430000      4.700000     16.430000
75%          13.900000     3.850000      6.000000     27.500000
max          42.830000    10.310000  90000.000000  70000.000000

In [8]:
cafe['country'].unique()

<StringArray>
[        'Denmark',           'China',             'USA',     'Switzerland',
       'Singapore',          'France',    'Saudi Arabia',              'UK',
         'Iceland',         'Finland',         'Germany',           'Qatar',
          'Russia',             'UAE',          'Turkey',          'Norway',
          'Sweden',         'Czechia',     'Netherlands',          'Taiwan',
         'Uruguay',         'Belgium',         'Ireland',          'Poland',
         'Austria',          'Canada',       'Lithuania',          'Greece',
          'Israel',      'Costa Rica',       'Australia',           'Japan',
          'Mexico',         'Estonia',            'Oman',         'Hungary',
        'Portugal',           'India',        'Slovakia',          'Kuwait',
            'Iraq',        'Maldives',         'Romania',          'Latvia',
         'Jamaica',           'Chile',       'Argentina',        'Malaysia',
          'Cyprus',           'Spain',     'El Salvador',     'New Zealand',
        'Bulgaria',         'Lebanon',     'South Korea',       'Kazakstan',
         'Ecuador',         'Croatia',        'Slovenia',         'Armenia',
          'Brazil',         'Vietnam',          'Serbia',       'Guatemala',
         'Moldova',     'Philippines',         'Bolivia',           'Malta',
           'Italy',         'Ukraine',       'Mauritius',       'Indonesia',
     'Puerto Rico',       'Nicaragua',    'South Africa',        'Colombia',
        'Pakistan',          'Jordan', 'North Macedonia',        'Djibouti',
         'Georgia',         'Belarus',       'Sri Lanka',         'Algeria',
        'Thailand',           'Egypt']
Length: 86, dtype: str

In [11]:
len(cafe['country'].unique())

86

In [12]:
cafe['country'].unique()

<StringArray>
[        'Denmark',           'China',             'USA',     'Switzerland',
       'Singapore',          'France',    'Saudi Arabia',              'UK',
         'Iceland',         'Finland',         'Germany',           'Qatar',
          'Russia',             'UAE',          'Turkey',          'Norway',
          'Sweden',         'Czechia',     'Netherlands',          'Taiwan',
         'Uruguay',         'Belgium',         'Ireland',          'Poland',
         'Austria',          'Canada',       'Lithuania',          'Greece',
          'Israel',      'Costa Rica',       'Australia',           'Japan',
          'Mexico',         'Estonia',            'Oman',         'Hungary',
        'Portugal',           'India',        'Slovakia',          'Kuwait',
            'Iraq',        'Maldives',         'Romania',          'Latvia',
         'Jamaica',           'Chile',       'Argentina',        'Malaysia',
          'Cyprus',           'Spain',     'El Salvador',     'New Zealand',
        'Bulgaria',         'Lebanon',     'South Korea',       'Kazakstan',
         'Ecuador',         'Croatia',        'Slovenia',         'Armenia',
          'Brazil',         'Vietnam',          'Serbia',       'Guatemala',
         'Moldova',     'Philippines',         'Bolivia',           'Malta',
           'Italy',         'Ukraine',       'Mauritius',       'Indonesia',
     'Puerto Rico',       'Nicaragua',    'South Africa',        'Colombia',
        'Pakistan',          'Jordan', 'North Macedonia',        'Djibouti',
         'Georgia',         'Belarus',       'Sri Lanka',         'Algeria',
        'Thailand',           'Egypt']
Length: 86, dtype: str

In [13]:
len(cappuccino_index['country'].unique())

87